name: Build and Push Compose Images
on: [push]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false
          
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true    
      - uses: actions/checkout@v3
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Services
        run: |
          docker compose build --build-arg HF_TOKEN=${{ secrets.HF_TOKEN }}
      
      - name: Tag and Push Images
        run: |
          docker tag sesame_csm_openai-csm-api ghcr.io/${{ github.repository }}/csm-api:latest
          docker push ghcr.io/${{ github.repository }}/csm-api:latest
